### PR TITLE
:arrow_up: Django 1.9.5

### PR DESCRIPTION
**Pull request by thraxil**

### CODE REVIEW

**Comment by sdreher** [comment]
The Wings templates override admin/base_site.html for several views, including login. With the style changes in 1.9.5, site rendering is in bad shape.

screen shot 2016-04-20 at 9 49 27 am

**Comment by thraxil** [comment]
hmm. the local version with 1.9.5 and the version at wings.ccnmtl.columbia.edu look pixel for pixel identical to me in Chrome.

**Comment by sdreher** [comment]
Weird. How are you handling static files locally? Maybe I'm doing something differently?

**Comment by thraxil** [comment]
Just the usual `make runserver`

**Comment by sdreher** [comment]
Okay, the issue seems to be that my dev environment is serving up the new Django admin/css. Nik sees "Eddie's Version" which is checked into the repo. I'll complete the merge.

Worth noting for the future: if/when Wings is ready to go to S3, a collectstatic will mess up rendering in a few errors.

**Pull request merged**
